### ISSUE TITLE
dns.get_qname not found

### ISSUE THREAD

**Issue by logical-voice** [TuxInvader/nginx-dns#21]
I have installed nginx 1.25.1 + njs 0.8.0 and used "nginx-doh-and-dot-to-dns.conf" to setup DoH service.
After installation it doesn't work properly and I get the following errors in /var/log/nginx/error.log .

js function "dns.get_qname" not found while prereading client data, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:53
js exception: TypeError: (intermediae value)["bytesFrom"] is not a function at module (/etc/nginx/njs.d/dns/dns.js:28

**Comment by Dual-0** [comment]
look into #19. This helps me to get is working with nginx 1.25.2 + njs 0.8.0.
Unfortunately there are still a few log messages but DoT and DoH works.
